stolostron/search-v2-api

pkg/config/config.go
pkg/database/connection.go

Changing env variable `DB_PASSWORD` -> `DB_PASS`  so we are consistent with env var throughout search components.

changing password to pass

---

pkg/resolver/searchComplete.go

Fixes problem where Search UI goes blank when SearchComplete returns no values. The API should return an empty array instead of null.
Verified deleting the postgres pod.

SearchComplete should return empty array instead of null

---

pkg/resolver/search.go
pkg/resolver/search_test.go

**Related Issue:**  stolostron/backlog#22013
Select distinct results during keyword search to avoid duplicate results when searching for kind:Pod search

select distinct results for search

---

build/run-lint-check.sh

Show lint errors clearly instead of 0/1 evaluation

update lint script

---

pkg/rbac/authzMiddleware.go
pkg/rbac/sharedData.go

**Related Issue:**  stolostron/backlog#22013
ManagedCluster cache in sharedData should not contain local-cluster.

Remove local-hub from managedCluster cache

---

pkg/resolver/search.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/26006
To avoid the issue we saw in PM cluster where Pods had apigroup set. Since data was defined outside, it leaked properties while looping. Moving the declaration inside. @zlayne

Avoid leaking properties in loop

---

pkg/resolver/search.go
pkg/resolver/search_test.go

**Related Issue:**  stolostron/backlog#22013
Users should be able to search by keyword without worrying about case sensitivity. This PR fixes current logic to use a case insensitive like clause

Case insensitive keywords

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/related.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchSchema.go

**Related Issue:**  [stolostron/backlog#25996](https://github.com/stolostron/backlog/issues/25996)
Remove rbac workaround for kubeadmin
For users to get the correct SSRR, all provided user info should be passed to impersonation config.
Just passing username and UID will not suffice to create the correct SSRR, if other info like groups and extra are present in token review.

remove kubeadmin workaround

---

pkg/rbac/sharedData.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/rbacHelper.go
pkg/resolver/related.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchSchema.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

**Related Issue:**  stolostron/backlog#22013 - Optimize RBAC for kubeadmin level access
Before creating SSRR and SSAR for each namespace and resource - check if user has kubeadmin level access/access to all resources. This will bypass ns level checks and make it easier for kubeadmin level  users.

check if user has access to all resources

---

pkg/database/connection.go
pkg/resolver/mocks/mock-related-test.json
pkg/resolver/related.go
pkg/resolver/related_test.go
pkg/resolver/search.go
pkg/resolver/testHelper_test.go

**Related Issue:**  stolostron/backlog#26115
- Fixes related items returning null when the relatedKinds filter is not included in the query.
- Fixes the case of the `kind` property on related items to match the search results.
Tested with this script:
```bash
oc create route passthrough search-api --service=search-search-api -n open-cluster-management
export URL="https://$(oc get route search-api -n open-cluster-management | awk 'NR==2' |awk '{print $2;}')/searchapi/graphql"
export TOKEN=$(oc whoami -t)
curl --insecure --location \
--request POST $URL \
--header "Authorization: Bearer $TOKEN" --header 'Content-Type: application/json' \
--data-raw '{"query":"query q($input: [SearchInput]) { search(input: $input) { related { kind count …
```

Fixes null related items and case of kind property

---

pkg/rbac/userData.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/22013
- Parallelize API calls to build cluster-scoped
- **Reduces function time from 2.5s to ~125ms.**

Parallelize API calls to build cluster-scoped access (SSAR)

---

pkg/rbac/cache.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go

- Continuation of 
- #114 and 
- #115 
- Simplify cache and manage data fields consistently using `cacheFieldMgmt{}`

Another refactor to simplify cache and keep consistency

---

pkg/rbac/cache.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go

- Replace the kube `corev1Client` with the `dynamicClient` to simplify and avoid using different clients.

Refactor: Consolidate kube clients for simplicity

---

go.mod
go.sum
gqlgen.yml
graph/generated/generated.go
graph/schema.resolvers.go
pkg/metric/slowLog_test.go
pkg/resolver/related.go
pkg/resolver/related_test.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go
pkg/resolver/searchHelper.go
pkg/resolver/searchSchema.go
pkg/resolver/searchSchema_test.go
pkg/resolver/search_test.go

1. Make `make gqlgen` work.
2. Remove panic and log error if no rbac clause is present.
3. Resolve the panic in case property type is not found in the propTypeMap.
W1014 11:46:18.551666   59092 search.go:304] Property type for [component] doesn't exist in cache. Refreshing property type cache
```
W1101 04:37:08.063988       1 search.go:299] Property type for [kind] doesn't exist in cache. Refreshing property type cache
W1101 04:37:08.064019       1 search.go:299] Property type for [kind] doesn't exist in cache. Refreshing property type cache
runtime error: invalid memory address or nil pointer dereference
goroutine 37037 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 …
```

remove panic if no rbac

---

pkg/rbac/tokenReview.go
pkg/rbac/tokenReview_test.go
pkg/rbac/userData_test.go

- Use common `cacheMetadata` to manage the tokenReview cache.

Simplify tokenreview cache

---

pkg/config/config.go
pkg/database/connection.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-3071
- Rename `DB_MAX_CONNS` to be consistent with recent change in indexer.

ACM-3071 Rename DB_MAX_CONNS to be consistent with indexer

---

README.md
go.mod
go.sum
pkg/database/connection.go
pkg/metric/metric.go
pkg/metric/middleware.go
pkg/metric/middleware_test.go
pkg/rbac/authnMiddleware.go

https://issues.redhat.com/browse/ACM-3228
- Add prometheus metrics middleware to capture request duration and response code
Send a query with invalid auth token
```
$ curl --insecure --location \ 
--request POST $URL \
--header "Authorization: Bearer $TOKEN" --header 'Content-Type: application/json' \
--data-raw '{"query":"query q($input: [SearchInput]) { search(input: $input) { count } }","variables":{"input":[{"keywords":[],"filters":[{"property":"kind","values":["ConfigMap"]}]}]}}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   201  100    28  100   173    139    860 --:--:-- --:--:-- --:--:--  1020
{
"message": "Invalid token"
}
```
Get the metrics
```
$ curl --insecure --location --request GET …
```

ACM-3228 Add prometheus metrics middleware to capture request duration and response code

---

Makefile
README.md
pkg/metric/metric.go
pkg/metric/middleware.go
pkg/server/server.go

https://issues.redhat.com/browse/ACM-3288
- Use a custom prometheus registry to exclude scraping requests (/metrics) from the returned data.
- Rename metric
- Add Make target to setup database for local dev.

ACM-3288 Exclude scraping requests from prom data

---

Makefile
pkg/metrics/metrics.go
pkg/metrics/middleware.go
pkg/metrics/middleware_test.go

https://issues.redhat.com/browse/ACM-4523
Add remoteAddr and userAgent labels to request metrics.

ACM-4523 Capture remoteAddr and userAgent in request metrics

---

README.md

- Previous publish build didn't succeed. 
https://github.com/stolostron/search-v2-api/pull/154
didn't get pulled into the latest snapshot, which is still showing the April 13 commit level:
https://github.com/stolostron/pipeline/blob/2.8-integration/snapshots/manifest-2023-05-03-03-36-16-2.8.0.json
So, retriggering with this dummy PR.

rebuild prow

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/rbacHelper.go
pkg/resolver/related.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-7062
- Implement the role `searches/allManagedData` which grants the global search user access to all resources from managed clusters.

ACM-7062: Special RBAC handling for global search user

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go

https://issues.redhat.com/browse/ACM-7857
- Fixes map concurrency error. UserData had maps that weren't correctly copied and contained references to the objects in the cache. This caused concurrency problems if the cache gets updated while using the copy on UserData.

ACM-7857 Deep copy UserData to avoid concurrency problems

---

pkg/resolver/searchComplete.go

N/A
- Ignore gosec G6002 which causes prow build to fail.  The main branch already has this change.

[release-2.8]  Ignore gosec G602 because of false positive.

---

pkg/federated/client.go

Fixes problem using client from the pool.
```
panic: interface conversion: interface {} is *federated.RealHTTPClient, not *http.Client
goroutine 1117 [running]:
github.com/stolostron/search-v2-api/pkg/federated.GetHttpClient({{0x1a1c903, 0xa}, {0x1a4ae75, 0x28}, {0xc000a21600, 0x513}, {0x0, 0x0}, {0x0, 0x0}})
github.com/stolostron/search-v2-api/pkg/federated/client.go:17 +0x374
github.com/stolostron/search-v2-api/pkg/federated.HandleFederatedRequest.func1({{0x1a1c903, 0xa}, {0x1a4ae75, 0x28}, {0xc000a21600, 0x513}, {0x0, 0x0}, {0x0, 0x0}})
github.com/stolostron/search-v2-api/pkg/federated/federated.go:59 +0xd8
created by github.com/stolostron/search-v2-api/pkg/federated.HandleFederatedRequest …
```

[federation side branch] Fix client pool

---

pkg/resolver/search.go

https://issues.redhat.com/browse/ACM-8950
- Return if error while fetching property type
Return as soon as error occurs:
```
E1207 13:46:05.894476       1 sharedData.go:87] Error resolving property types query [SELECT DISTINCT key, jsonb_typeof("value") AS "datatype" FROM "search"."resources", jsonb_each("data")] with args [context canceled]. Error: [%!v(MISSING)]
E1207 13:46:05.894488       1 sharedData.go:127] Error retrieving property types. Error: [context canceled]
E1207 13:46:05.894554       1 search.go:308] Error creating property type map with err: [context canceled] 
runtime error: invalid memory address or nil pointer dereference
```

ACM-8950 return if error while fetching property type

---

pkg/federated/README.md
pkg/federated/cleanup.sh
pkg/federated/setup.sh

https://issues.redhat.com/browse/ACM-9302
- Simplify usage of setup.sh and cleanup.sh scripts by including the yaml templates inline.
- Improve cleanup.sh to check if ManagedServiceAccount is being used in the cluster before disabling.
- Update README.md

ACM-9302: Update federated search setup and cleanup scripts

---

pkg/rbac/sharedData.go

https://issues.redhat.com/browse/ACM-14996
- Messages query was not properly handling the ManagedCluster array when the user has access to all Resources (userData.ManagedClusters = map[*:{}])

[ACM-14996] Fix Messages query to get disabled clusters

---

pkg/config/config.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchHelper.go
pkg/resolver/searchSchema.go

N/A
- Change  limit to `uint` to fix gosec warnings.

Fix gosec errors converting to uint

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go

https://issues.redhat.com/browse/ACM-14946
- Require apigroup when checking that user has access to create `managedclusterview.cluster.open-cluster-management.io`

ACM-14946: Require apigroup when checking managedclusterview authorization

---

pkg/resolver/searchHelper.go
pkg/resolver/searchHelper_test.go

This is helpful to have a mapping of keys to counts. By keeping it as a number in the database instead of converting it as part of the indexing, it allows formatting it differently in the future.
This is required by https://github.com/stolostron/search-collector/pull/327.
Relates:
https://issues.redhat.com/browse/ACM-15127

Add support for integer values in map properties

---

pkg/config/config.go

https://issues.redhat.com/browse/ACM-13201
Reduced the default `DB_MAX_CONN_LIFE_TIME` to 1 minute to reduce the overall memory utilization in postgres.
Postgres connections cache the resources that is uses on the postgres server. Every time the connection is used, new data is cached, increasing the memory utilization. With this change, connections are closed more often allowing the postgres server to release the memory used for caching.

ACM-13201 :Update postgres conn pool to reduce memory utilization

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go

https://issues.redhat.com/browse/ACM-16126
- The rbac check for managedclusterview was using the incorrect apigroup.
- Updated to use `view.open-cluster-management.io/v1beta1`
```bash
$ oc api-resources |grep managedclusterview
managedclusterviews       view.open-cluster-management.io/v1beta1       true      ManagedClusterView
```

ACM-16126: Fix incorrect apigroup on managedclusterview check

---

graph/generated/generated.go
graph/schema.graphqls
graph/schema.resolvers.go
pkg/resolver/searchSchema.go
pkg/resolver/searchSchema_test.go
pkg/resolver/testHelper_test.go

https://issues.redhat.com/browse/ACM-17849
- Added ...

[ACM-17849] Filter searchSchema results based on current search query params

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod
pkg/resolver/related_test.go

https://issues.redhat.com/browse/ACM-18716
- UBI 9
- Go 1.23

ACM-18716 Update to go 1.23 and UBI 9

---

.tekton/search-v2-api-acm-214-pull-request.yaml

- Added image-digest param to sast-coverity-check-oci-ta to fix https://github.com/stolostron/search-v2-api/pull/444

fix sast-coverity-check-oci-ta by adding missing image-digest
