Dockerfile.prow
Makefile.prow
OWNERS

Related Issue: https://github.com/stolostron/backlog/issues/18042
Description:
- Adds OWNERS file, Dockerfile.prow , and Makefile.prow for use in prow build pipeline.

Onboard to prow

---

Dockerfile
Dockerfile.prow
go.mod
gqlgen.yml
graph/generated/generated.go
graph/schema.resolvers.go
main.go
pkg/database/connection.go
pkg/resolver/related.go
pkg/resolver/search.go
pkg/resolver/search_test.go
pkg/schema/searchComplete.go
pkg/schema/searchSchema.go
pkg/server/server.go

- Update project references from open-cluster-management to stolostron.

Update project references to stolostron

---

pkg/resolver/related.go
pkg/resolver/search.go
pkg/resolver/search_test.go
pkg/schema/searchComplete.go
pkg/schema/searchSchema.go

Add schema to table names

---

Makefile
Makefile.prow
graph/generated/generated.go
graph/schema.resolvers.go
pkg/resolver/related.go
pkg/resolver/search.go

- Merges changes from #2 
**NOTE:** This code will be refactored to improve query performance and add tests.  Merging this incomplete code to unblock the team.

Merge relationships PR

---

main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/database/connection.go
pkg/resolver/mocks/mock-rel-1.json
pkg/resolver/search.go
pkg/resolver/searchComplete_test.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

For https://github.com/stolostron/backlog/issues/20282
Rewrite relations query with goqu template
~Add relatedKinds filter~

Rewrite relations query with goqu

---

README.md

This PR is solely to test image-mirror job that failed recently and contains only a small indentation update to ReadME

No-op PR to test image-mirror job

---

pkg/resolver/search.go

The issue was in the `buildSearchQuery`. Adding `jsonb_each_text(data)` in the from clause when there were no keywords caused duplicates.

Fix duplicate results error

---

README.md

https://github.com/stolostron/backlog/issues/21303

Rebuild 2.5

---

README.md

No-op PR to remediate package vulnerability bug
Related issue: [22040](https://github.com/stolostron/backlog/issues/22040)

No-op PR for search-v2-api package vulnerability bug

---

pkg/resolver/searchSchema.go

Issue: https://github.com/stolostron/backlog/issues/22013
Remove properties that start with underscore(_) from the searchSchema because these are internal and not meant to be exposed to end users.

Remove properties starting with underscore(_) from searchSchema suggestions

---

pkg/config/config.go
pkg/config/config_test.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go

Issue: N/A
- Cleanup the environment variables in `config.go`.
- Add unit tests

Cleanup environment variables in config.go

---

go.mod
pkg/config/kubeCilent.go
pkg/rbac/middleware.go
pkg/resolver/mocks/mock.json
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go
pkg/resolver/searchSchema_test.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

**Related Issue:**  [stolostron/backlog#20787](https://github.com/stolostron/backlog/issues/20787)
Add searchComplete and search support for date and number filters

updates for date and num filter

---

pkg/config/config.go
pkg/config/config_test.go
pkg/database/connection.go

**Related Issue:**  stolostron/backlog#21297
- Make SSL required for postgre client connection.

Require SSL on Postgre connection

---

pkg/rbac/authenticationMiddleware.go
pkg/rbac/authenticationMiddleware_test.go
pkg/server/server.go

**Related Issue:**  stolostron/backlog#[22506](https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/22506)
Unit tests for AuthenticateUser middleware

Unit tests for token retrieval middleware

---

README.md

**Related Issue:**  stolostron/backlog#22555
no-op pr to resolve image scan - merging on release branch 2.6

no-op pr to resolve image scan

---

graph/schema.graphqls

Signed-off-by: Joydeep Banerjee <jbanerje@redhat.com>
Typos and grammar.

typo correction

---

.gitignore
Makefile
test/locust-users.py
test/search-query-template.json

**Related Issue:**  stolostron/backlog#19286
Adds initial scalability (locust) tests.

Initial scale test (locust)

---

pkg/resolver/related_test.go
pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go
pkg/resolver/searchSchema_test.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

If limit is set in searchComplete, return results specified by limit.

Use limit set in Search complete

---

graph/generated/generated.go
graph/model/models_gen.go
graph/schema.graphqls
graph/schema.resolvers.go

Signed-off-by: Zack Layne <zlayne@redhat.com>
**Related Issue:**  stolostron/backlog#23869
/hold until https://github.com/stolostron/console/pull/1818 is merged.

Remove placeholder gql code for saved search query and mutations

---

pkg/config/kubeCilent.go
pkg/rbac/authzMiddleware.go

Few changes to improve performance for initial authorization.

 rbac improve performance

---

OWNERS
README.md

**Related Issue:**  https://github.com/stolostron/backlog/issues/24878
- Update OWNERS and trigger prow to publish 2.7

Update OWNERS and trigger prow to publish 2.7

---

pkg/rbac/authnMiddleware.go
pkg/rbac/authnMiddleware_test.go
pkg/rbac/authzMiddleware.go
pkg/rbac/cache.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/tokenReview.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/rbacHelper.go
pkg/resolver/related_test.go
pkg/resolver/search.go
pkg/resolver/searchComplete_test.go
pkg/resolver/searchSchema_test.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/21298
- Adds RBAC WHERE clause to the search queries.

Add where clause for rbac

---

pkg/rbac/userData.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchSchema.go
pkg/resolver/testHelper_test.go

Skipping RBAC temporarily for kubeadmin

workaround for kubeadmin

---

pkg/resolver/searchSchema.go

fix schema

---

pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go
pkg/resolver/searchSchema_test.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/21298
Updated managedclusters in shareddata and userdata to map
updated getKeys function to take any map input

update struct managedclusters and getKeys function

---

Makefile

- Fixes problem where make hangs when oc is not connected to a cluster.

Fixes make  command seems unresponsive

---

pkg/resolver/rbacHelper.go
pkg/resolver/search_test.go

**Related Issue:**  stolostron/backlog#25990
Either or Both apigroup and kind '*'

Handle stars (wildcards *) in permissions

---

pkg/resolver/related.go

Related to https://github.com/stolostron/search-v2-api/pull/85
Skipping RBAC temporarily for kubeadmin - for related query

add kubeadmin workaround for related query

---

pkg/metric/middleware.go
pkg/rbac/sharedData.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/search.go

**Related Issue:**  stolostron/backlog#25996
Update user's managed clusters too if user has access to that namespace
Correct logs without formatting in the Infof.

update user's managedcluster list

---

pkg/rbac/authzMiddleware.go
pkg/rbac/cache.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/userData.go

- Separates SharedData cache from Cache.
- Changes the scope of several functions from `func (cache *Cache)` to `func(shared *SharedData)`

Refactor shared data cache

---

pkg/database/connection.go
pkg/rbac/authzMiddleware.go
pkg/rbac/cache.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/26447

Fixes DB connection issue

---

pkg/config/config.go
pkg/metric/slowLog.go
pkg/metric/slowLog_test.go
pkg/rbac/authzMiddleware.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/userData.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/22013
- Parallelize shared cache API requests.
- Add func to log slow queries

Parallelize shared cache and add func to log slow queries

---

pkg/rbac/userData.go

**Related Issue:**  stolostron/backlog#22013
- Use an async go routine for each namespace SSRR request.

Parallelize SSRR requests for namespaces

---

pkg/rbac/sharedData_test.go
pkg/rbac/userData.go
pkg/rbac/userData_test.go

- Refactor to simplify access to objects in UserDataCache.

Refactor to simplify UserData cache

---

pkg/rbac/cache.go
pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/rbac/userData.go

- Refactor to consolidate cache management fields into a common struct.

Refactor to simplify management of cached data

---

pkg/rbac/userData.go

- Simplify using common isValid() from cacheMetadata.

Use common isValid from cacheMetadata

---

pkg/rbac/userData.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-2170
- Remove unnecessary locking which is causing problems.

Fixes UserData locking

---

pkg/config/config.go
pkg/database/connection.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-3071

update max connections to 10

---

pkg/rbac/userData.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-2830
- Add missing lock when reading managed clusters

Fix missing clusters on user's cache

---

OWNERS
pkg/config/config.go
pkg/database/connection.go
pkg/rbac/userData.go

- https://issues.redhat.com/browse/ACM-2830
- https://issues.redhat.com/browse/ACM-3071

[release-2.7] Cherry-pick fixes for ACM-2830 and ACM-3071

---

main.go
pkg/database/connection.go
pkg/rbac/cache.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchSchema.go

NA
- Renamed GetConnection() to GetConnPool() for clarity.
- Pass context to `GetConnPool(ctx context.Context)`
- Removed redundant `if rows != nil`

Refactor: Tidy up code

---

pkg/resolver/search.go
pkg/resolver/searchHelper.go

https://issues.redhat.com/browse/ACM-4170
- Update query when it includes the `cluster` property.

ACM-4170 fix not operator for cluster property

---

pkg/database/connection.go
pkg/resolver/search.go
pkg/resolver/searchHelper.go

https://issues.redhat.com/browse/ACM-4523
- Reduce log verbosity to reduce noise.
- Refactor to use SlowLog()

ACM-4523 Reduce logging and use SlowLog function

---

pkg/config/config.go
pkg/rbac/cacheMetadata_test.go
pkg/rbac/sharedData_test.go

https://issues.redhat.com/browse/ACM-5181
- Increase cache time

[ACM 5181] increase cache time

---

sonar-project.properties

> 14:59:29.980 ERROR: Unable to parse file: file:///go/src/github.com/stolostron/search-v2-api/graph/generated/generated.go. 
> 14:59:29.980 ERROR: Cannot parse 'graph/generated/generated.go': Go parser external process returned non-zero exit value: 2
> 14:59:29.979 DEBUG: panic: -:443:40: illegal character U+FFFD '?' (and 62 more errors)
in https://storage.googleapis.com/origin-ci-test/logs/branch-ci-stolostron-search-v2-api-main-sonar-post-submit/1653775116464558080/build-log.txt
- Added ...

exclude generated files from sonar

---

Dockerfile
go.mod

https://issues.redhat.com/browse/ACM-5513
- Upgrade go to v1.20

ACM-5513: Upgrade to go v1.20

---

Dockerfile
Makefile
Makefile.prow
go.mod
pkg/resolver/testHelper_test.go

https://issues.redhat.com/browse/ACM-5513
- Update go to v1.20

[release-2.7] ACM-5513: Update go to v1.20

---

graph/schema.resolvers.go
pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go

Workaround for https://issues.redhat.com/browse/ACM-5242
- Remove higher limit in inner query.
- Ignore limit if -1

Remove limit in inner query for Search complete

---

pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go

https://app.travis-ci.com/github/stolostron/canary/builds/263795869
- Added ...

fix autocomplete with cluster property

---

pkg/config/config.go
pkg/database/connection.go

https://issues.redhat.com/browse/ACM-5168
- Ping DB connection before acquiring from pool to prevent issues when connections are terminated.
Will wait to merge for release-2.9 because this repo already has a connection check. This change is only to keep consistency with search-indexer.

Test connection before acquiring from pool

---

pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go

use jsonb operator in where clause

---

pkg/rbac/userData.go
pkg/resolver/searchComplete.go

https://issues.redhat.com/browse/ACM-7062
- Check the search apigroup while creating the SSAR

ACM-7062 check apigroup for global search user

---

pkg/resolver/rbacHelper.go
pkg/resolver/related.go
pkg/resolver/related_test.go
pkg/resolver/search_test.go

Fix kind cluster search

---

pkg/rbac/dbAvailability.go
pkg/rbac/dbAvailability_test.go
pkg/server/server.go

https://github.com/stolostron/backlog/issues/27385
- Added ...

Refresh cache for all requests

---

README.md

Dummy PR to trigger prow rebuild.

Trigger prow rebuild

---

README.md

N/A
- Dummy PR to trigger prow build

Trigger prow again

---

pkg/federated/client.go
pkg/federated/federated.go
pkg/federated/federated_test.go
pkg/federated/parseResponse.go

Add getFederatedResponse function

---

pkg/federated/federated.go
pkg/federated/federated_test.go

remove mockClientPool

---

pkg/federated/client.go
pkg/federated/federated.go
pkg/federated/federated_test.go

mock GetHttpClient function

---

Makefile
pkg/federated/mergeResponses.go
pkg/federated/mergeResponses_test.go

https://issues.redhat.com/browse/ACM-8775
- Implement relationships for Global Search.

ACM-8775: Global search merge relationships

---

pkg/federated/README.md
pkg/federated/cleanup.sh
pkg/federated/setup.sh

N/A
- Add **limitations** section to federated readme.
- Update setup.sh to reset the managed hub configurations.
- Simplify cleanup.sh script

Update federated search setup and readme

---

pkg/federated/README.md

N/A
- Minor edits to federated README.

Edits to federated README

---

pkg/resolver/search.go
pkg/resolver/searchHelper.go
pkg/resolver/search_test.go
pkg/resolver/testHelper_test.go

https://issues.redhat.com/browse/ACM-10578
- Added ...

[ACM-10578] WIP: partial match

---

pkg/rbac/userData.go
pkg/resolver/searchHelper.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-10578
- Enabled partial match for array and object properties.

[ACM-10578] - partial match label

---

pkg/rbac/sharedData.go
pkg/rbac/sharedData_test.go
pkg/resolver/searchHelper.go

https://issues.redhat.com/browse/ACM-10019
- Added managedHub propType

ACM-10019 - 1. add managedHub property type to cache

---

pkg/resolver/related.go
pkg/resolver/related_test.go
pkg/resolver/search.go
pkg/resolver/searchHelper.go
pkg/resolver/testHelper_test.go

https://issues.redhat.com/browse/ACM-10019
- export helper functions

ACM-10019 - 2. export helper functions

---

pkg/federated/federated_test.go
pkg/federated/mergeResponses.go
pkg/federated/mergeResponses_test.go

https://issues.redhat.com/browse/ACM-10019
- Added managedHub to federated searchSchema

ACM-10019 - 3. update searchSchema with managedHub

---

go.mod
pkg/config/config.go
pkg/federated/federated_test.go
pkg/federated/mergeResponses.go
pkg/resolver/search.go
pkg/resolver/searchHelper.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-10019
- check if to proceed with Search based on ManagedHub filter

ACM 10019 - enable managedHub Search

---

pkg/federated/federated_test.go
pkg/resolver/searchHelper.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-11654
- Added ...

ACM 11654 - fix not equal to array operation

---

pkg/resolver/searchComplete.go
pkg/resolver/searchComplete_test.go

https://issues.redhat.com/browse/ACM-10019 
- Added ...

ACM 10019 - 4. managedHub SearchComplete

---

pkg/resolver/search.go
pkg/resolver/searchHelper.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-11654
- Added ...

ACM 11654 - 5. Partial match managed hub

---

pkg/rbac/sharedData.go

https://issues.redhat.com/browse/ACM-14996
- Refactor changes merged with PR #253 
- This doesn't change the behavior, so no need to cherry-pick to release branches.

Refactor change to disabledClustersForUser() from PR #253

---

pkg/config/config.go
pkg/resolver/search.go
pkg/resolver/searchComplete.go
pkg/resolver/searchHelper.go
pkg/resolver/searchSchema.go

https://github.com/stolostron/search-v2-api/pull/262
- Added ...

[release-2.10] Fix gosec errors converting to uint

---

.tekton/search-v2-api-acm-213-pull-request.yaml
.tekton/search-v2-api-acm-213-push.yaml
Dockerfile

N/A
- Merge release-2.13 into main to fix fast-forward.

Merge konflux updates from release-2.13 to main

---

pkg/config/config.go

https://issues.redhat.com/browse/ACM-13201
- Updates pgxpool connection settings to match the [settings on the indexer](https://github.com/stolostron/search-indexer/pull/233).

ACM-13201: Update pgxpool conn settings to match indexer

---

renovate.json

N/A
- Update Konflux renovate.json to reduce the amount of PRs generated.

Update konflux renovate.json config

---

.tekton/search-v2-api-acm-211-pull-request.yaml
.tekton/search-v2-api-acm-211-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.11] Update Konflux config

---

.tekton/search-v2-api-acm-210-pull-request.yaml
.tekton/search-v2-api-acm-210-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.10] Update Konflux config

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod
pkg/resolver/related_test.go

cherry-pick of https://github.com/stolostron/search-v2-api/pull/379

release-2.13 ACM-18716 Update to go 1.23 and UBI 9 (#379)

---

Dockerfile
Dockerfile.rhtap
go.mod
go.sum

Manual cherry-pick of https://github.com/stolostron/search-v2-api/pull/378

release-2.12 ACM-18716 Update to go1.22 (#378)

---

Makefile
Makefile.prow
pkg/resolver/related.go
pkg/resolver/search.go

[release-2.12] Update lint and fix errors

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod
pkg/resolver/related_test.go

cherry-pick of https://github.com/stolostron/search-v2-api/pull/379

2.12 ACM-18716 Update to go 1.23 and UBI 9 (#379)

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
pkg/resolver/related.go
pkg/resolver/search.go

- Added .ci-operator.yaml file to empower prow :muscle: to run
- Update Go to 1.23

[release-2.11] update to go 123

---

.ci-operator.yaml
Dockerfile
Makefile
Makefile.prow
go.mod
pkg/resolver/related.go
pkg/resolver/search.go

- Added .ci-operator.yaml and updated go to 1.23

[release-2.9] update go to 1.23

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
pkg/resolver/related.go
pkg/resolver/search.go

- Added .ci-operator.yaml and updated go to 1.23

[release-2.10] update go to 1.23

---

go.mod
go.sum

[release-2.9] fix cve-2025-22868/22869

---

.tekton/search-v2-api-acm-214-pull-request.yaml
.tekton/search-v2-api-acm-214-push.yaml
Dockerfile
Dockerfile.rhtap
renovate.json

N/A
- [Enabling hermetic builds in Konflux](https://konflux.pages.redhat.com/docs/users/building/hermetic-builds.html)
- [Prefetching package manager dependencies for hermetic builds](https://konflux.pages.redhat.com/docs/users/building/prefetching-dependencies.html)
- Updates renovate.json

Enable konflux hermetic builds

---

.tekton/search-v2-api-acm-214-pull-request.yaml
.tekton/search-v2-api-acm-214-push.yaml
Dockerfile
Dockerfile.locust
Dockerfile.rhtap

N/A
- Fix konflux hermetic builds.
- Update image labels

Fix konflux hermetic builds

---

.github/renovate.json

N/A
- Move renovate.json and update package grouping

Move renovate.json and update package grouping

---

.tekton/search-v2-api-acm-211-pull-request.yaml

- Added missing params image-digest and image-url to fix https://github.com/stolostron/search-v2-api/pull/445

[release-2.11] fix sast-snyk-check add missing params

---

.tekton/search-v2-api-acm-210-pull-request.yaml

- cherry-pick of https://github.com/stolostron/search-v2-api/pull/460/files to fix konflux failures

[release-2.10] fix sast-snyk-check add missing params

---

.tekton/search-v2-api-acm-210-pull-request.yaml

- moved params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8

[release-2-.10] fix sasy-snyk-check params

---

.tekton/search-v2-api-acm-211-pull-request.yaml

- moved params according tto https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8

[release-2.11] fix sast-snyk-check params

---

.tekton/search-v2-api-acm-214-push.yaml

Fix konflux on-push config

---

.tekton/search-v2-api-acm-210-push.yaml

[release-2.10] fix konflux on push

---

.tekton/search-v2-api-acm-211-push.yaml

[release-2.11] fix konflux on push config

---

pkg/database/connection.go
pkg/rbac/cache.go
pkg/rbac/userData.go
pkg/resolver/messages.go

N/A
- Reduce logging on unit tests and db connection error scenarios.

Reduce logging

---

pkg/rbac/sharedData.go
pkg/resolver/rbacHelper.go
pkg/resolver/search_test.go

https://issues.redhat.com/browse/ACM-20492
- Removed hard-coded "local-cluster" by grabbing cluster name from database and by grabbing all managed cluster names that don't have local-cluster label

ACM-20492 remove hard-coded local-cluster

---

pkg/database/connection.go
pkg/rbac/cache.go

N/A
- Fixes regression introduced by PR #500

Fix database conn regression

---

pkg/resolver/related.go
pkg/resolver/search.go

- Made corrections to mistakes made in https://github.com/stolostron/search-v2-api/commit/b8ad4ba6667e487c518ce2630cac82662cdbf322#diff-86e543ee2134ab885b268ea2c4f500c9f7b4e598d5af93215b092d5cfdb3b766 when updating Go to 1.23 and incorporating changes from https://github.com/stolostron/search-v2-api/pull/249/files

[release-2.12] fix search input keyword and input checks

---

pkg/resolver/searchComplete.go

manual cherry-pick of https://github.com/stolostron/search-v2-api/pull/520

[release-2.12] add missing jsonb_each_text

---

pkg/rbac/userData.go
pkg/rbac/userData_test.go
pkg/resolver/rbacFineGrainedHelper.go
pkg/resolver/rbacHelper.go
pkg/resolver/search.go

N/A
- The response from kubevirtproject.clusterview.open-cluster-management.io changed. This updates how we read it.

Fix fine-grained RBAC

---

README.md

- noop after removing 2.14 konflux config from main/2.15

[release-2.14] konflux noop

---

.tekton/search-v2-api-acm-214-pull-request.yaml

N/A
- Update konflux to run on PRs to release-2.14

[release-2.14] Update konflux to run on PRs to release-2.14

---

.tekton/search-v2-api-acm-215-pull-request.yaml
.tekton/search-v2-api-acm-215-push.yaml

- Added multi-arch builds back, hermetic builds, other params konflux missed with the 2.15 config

[main] hermetic, multi-arch, params konflux fix

---

.tekton/search-v2-api-acm-212-pull-request.yaml
.tekton/search-v2-api-acm-212-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.12] multiarch hermetic builds

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

[release-2.11] update go to 1.24
